package com.hblib.demoforspring.pojo;

public class ToolistDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toollist.id
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toollist.name
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toollist.user_id
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toollist.id
     *
     * @return the value of toollist.id
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toollist.id
     *
     * @param id the value for toollist.id
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toollist.name
     *
     * @return the value of toollist.name
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toollist.name
     *
     * @param name the value for toollist.name
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toollist.user_id
     *
     * @return the value of toollist.user_id
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toollist.user_id
     *
     * @param userId the value for toollist.user_id
     *
     * @mbg.generated Sat Apr 20 14:16:04 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}